/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brandCocoaBrown: "#362c26",
        brandCloudy: "#a9a19d",
        brandBeaver: "#886153",
        brandPampas: "#f7f3f1",
        brandMuesli: "#af8164",
        brandCashmere: "#e6be9c",
        brandWafer: "#d7c5c0",
        brandAlmond: "#eed9c5",
        brandSilverSand: "#b1b7b8",
        brandJuniper: "#72948c",
        brandVanillaIce: "#f4d4d5",
        brandWhite: "#fefefe",
        brandAlabaster: "#f9f9f9",
        brandBlack: "#020202",
      },
      fontFamily: {
        biotifBold: ["biotif-bold", "sans-serif"],
        biotifBlack: ["biotif-black", "sans-serif"],
        biotifMedium: ["biotif-medium", "sans-serif"],
        biotifRegular: ["biotif-regular", "sans-serif"],
        avenirRoman: ["avenir-roman", "sans-serif"],
        avenirBlack: ["avenir-black", "sans-serif"],
        avenirBook: ["avenir-book", "sans-serif"],
        avenirMedium: ["avenir-medium", "sans-serif"],
        avenirHeavy: ["avenir-heavy", "sans-serif"],
        avenirRegular: ["avenir-regular", "sans-serif"],
        avenirLight: ["avenir-light", "sans-serif"],
      },
      dropShadow: {
        "3xl": "0 35px 35px rgba(0, 0, 0, 0.25)",
        navItem: "0px, 10px rgba(188, 186, 186, 0.25)",
      },
      fontSize: {
        xxs: "10px",
        fourRem: "4rem",
        fiveRem: "5rem",
        "10xl": "10rem",
        "12xl": "12rem",
        "14xl": "14rem",
        "16xl": "16rem",
        "18px": "18px",
        "14px": "14px",
        "22px": "22px",
        "24px": "24px",
        "30px": "30px",
        "42px": "42px",
      },
      borderRadius: {
        four: "0.25rem",
        five: "0.3125rem",
        six: "0.375rem",
        eight: "0.5rem",
        "8point66px": "0.54125rem",
        ten: "0.625rem",
        fifteen: "0.9375rem",
        twenty: "1.25rem",
        thirty: "1.875rem",
        forty: "2.5rem",
        "44.64px": "2.79rem",
        fifty: "3.125rem",
        sixty: "3.75rem",
        eighty: "5rem",
        hundred: "6.25rem",
        twoHundred: "12.5rem",
        twoFifty: "15.625rem",
        fiveHundred: "31.25rem",
        fiftyPercent: "50%",
      },
    },
  },
  plugins: [],
};
